"""Generic destructive-confirm modal &mdash; Cancel-on-left, Confirm-on-right, with backdrop click-to-dismiss and defensive form-submission guards. Codifies **Convention V12 (Destructive-confirm composition)** as running code."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/confirm_modal.ipynb.

# %% auto #0
__all__ = ['render_confirm_modal']

# %% ../../nbs/components/confirm_modal.ipynb #confirm-modal-imports
from typing import Any, Dict, Optional

from fasthtml.common import Dialog, Div, Form, Button, H3, FT

from cjm_fasthtml_daisyui.components.actions.modal import (
    modal, modal_box, modal_action, modal_backdrop,
)
from cjm_fasthtml_tailwind.utilities.spacing import m
from cjm_fasthtml_tailwind.utilities.typography import font_size, font_weight
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import (
    flex_display, items, gap,
)
from cjm_fasthtml_tailwind.core.base import combine_classes

from cjm_fasthtml_lucide_icons.factory import lucide_icon

from cjm_fasthtml_design_system.buttons import buttons
from cjm_fasthtml_design_system.icons import icons

# %% ../../nbs/components/confirm_modal.ipynb #confirm-modal-fn
def render_confirm_modal(
    modal_id:str, # HTML id for the <dialog> element
    body_id:str, # HTML id for the inner Div HTMX targets for message text
    title:str="Confirm Action?", # Modal title (rendered in <h3>)
    confirm_label:str="Confirm", # Right-button label
    confirm_icon:Optional[str]=None, # Optional Lucide icon name (e.g. "trash-2") prefixed to the confirm label
    cancel_label:str="Cancel", # Left-button label
    confirm_attrs:Optional[Dict[str, Any]]=None, # Caller-supplied attrs for the confirm button (hx_post / hx_vals / hx_swap / etc.)
) -> FT: # Dialog element implementing V12
    """Render a destructive-confirm modal (V12). Cancel-LEFT, Confirm-RIGHT, backdrop click-to-dismiss, defensive type=button. Body populated via HTMX swap into body_id."""
    confirm_attrs = dict(confirm_attrs or {})
    confirm_attrs.setdefault("type", "button")

    confirm_children = []
    if confirm_icon:
        confirm_children.append(lucide_icon(confirm_icon, size=icons.text_button))
    confirm_children.append(confirm_label)

    return Dialog(
        Div(
            H3(title, cls=combine_classes(font_size.lg, font_weight.bold)),
            Div(id=body_id, cls=str(m.y(4))),
            Div(
                Form(
                    Button(
                        cancel_label,
                        cls=str(buttons.soft_dismissal),
                        formmethod="dialog",
                    ),
                    method="dialog",
                ),
                Button(
                    *confirm_children,
                    cls=combine_classes(
                        buttons.destructive_confirm,
                        flex_display, items.center, gap(1),
                    ),
                    **confirm_attrs,
                ),
                cls=combine_classes(modal_action, flex_display, gap(2)),
            ),
            cls=str(modal_box),
        ),
        Form(Button("close"), method="dialog", cls=str(modal_backdrop)),
        id=modal_id,
        cls=str(modal),
    )
