"""Generic empty-state component &mdash; a centered icon-above-title-above-detail composition optionally including a call-to-action, composing V8 anatomy slots into a single rendering helper. Codifies **Convention V8 (Empty-state anatomy)** as running code per the V12 convention/implementation split: V8 anatomy stays design-system-owned (`cjm-fasthtml-design-system/nbs/empty_states.ipynb`); the rendering helper that composes those slots into FT lives here."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/empty_state.ipynb.

# %% auto #0
__all__ = ['render_empty_state']

# %% ../../nbs/components/empty_state.ipynb #empty-state-imports
from typing import Optional

from fasthtml.common import Div, P, FT

from cjm_fasthtml_lucide_icons.factory import lucide_icon

from cjm_fasthtml_design_system.icons import icons
from cjm_fasthtml_design_system.empty_states import empty_states

# %% ../../nbs/components/empty_state.ipynb #empty-state-fn
def render_empty_state(
    message:str, # Primary empty-state message (single sentence in the title slot)
    detail:Optional[str]=None, # Optional supporting line rendered below the title in the detail slot
    icon_name:Optional[str]=None, # Optional Lucide icon name; rendered at V11 icons.empty_state size with V8 icon opacity
    cta:Optional[FT]=None, # Optional call-to-action element appended as the last wrapper child (typically Button with V1 buttons.primary_action)
    id:Optional[str]=None, # Optional outer Div id (for HTMX targeting or consumer ID-schema integration)
) -> FT: # Div implementing V8 empty-state anatomy
    "Render a canonical empty-state component per V8 anatomy (icon &rarr; title &rarr; detail &rarr; CTA child ordering, all slots optional except message)."
    children = []
    if icon_name is not None:
        children.append(
            lucide_icon(icon_name, size=icons.empty_state, cls=empty_states.icon)
        )
    children.append(P(message, cls=empty_states.title))
    if detail is not None:
        children.append(P(detail, cls=empty_states.detail))
    if cta is not None:
        children.append(cta)

    div_kwargs = {"cls": empty_states.wrapper}
    if id is not None:
        div_kwargs["id"] = id
    return Div(*children, **div_kwargs)
