"""Step-level header band rendering helper &mdash; the title + optional subtitle on the left, optional trailing slot on the right composition that introduces each workflow step inside StepFlow's per-step render. Composes V2 anatomy slots into a single FT-returning helper. Codifies **Convention V2 (Step header band anatomy)** as running code per the V12 convention/implementation split: V2 anatomy stays design-system-owned (`cjm-fasthtml-design-system/nbs/step_chrome.ipynb`); the rendering helper that composes those slots into FT lives here."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/step_header_band.ipynb.

# %% auto #0
__all__ = ['render_step_header_band']

# %% ../../nbs/components/step_header_band.ipynb #step-header-band-imports
from typing import Optional

from fasthtml.common import Div, H2, P, FT

from cjm_fasthtml_design_system.step_chrome import step_header_band

# %% ../../nbs/components/step_header_band.ipynb #step-header-band-fn
def render_step_header_band(
    title:str, # Step title text (H2)
    subtitle:Optional[str]=None, # Optional subtitle text (P); hidden at M1/M2 via V2's responsive subtitle class
    trailing:Optional[FT]=None, # Optional right-side FT (single trigger, pre-wrapped multi-trigger Div, badge, etc.)
    id:Optional[str]=None, # Optional outer Div id (for HTMX targeting or consumer ID-schema integration)
) -> FT: # Div implementing V2 step header band anatomy
    "Render a canonical step-level header band per V2 anatomy (title block on the left, optional trailing on the right). Responsive compression at the M2/M3 boundary is encoded in the V2 slot class strings; no per-call knobs needed."
    title_block_children = [H2(title, cls=step_header_band.title)]
    if subtitle is not None:
        title_block_children.append(P(subtitle, cls=step_header_band.subtitle))
    title_block = Div(*title_block_children)

    outer_children = [title_block]
    if trailing is not None:
        outer_children.append(trailing)

    outer_kwargs = {"cls": step_header_band.layout}
    if id is not None:
        outer_kwargs["id"] = id
    return Div(*outer_children, **outer_kwargs)
