"""Routing utilities for FastHTML applications"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/routing.ipynb.

# %% auto #0
__all__ = ['register_routes', 'APIRouter']

# %% ../../nbs/core/routing.ipynb #m3n4o5p6
from functools import partialmethod
from typing import Any
import fasthtml.common as _ft

# %% ../../nbs/core/routing.ipynb #u1v2w3x4
def register_routes(
    app,  # FastHTML app instance
    *routers  # One or more APIRouter instances to register
) -> None:  # No return value
    """Register multiple APIRouter instances to a FastHTML app at once."""
    for router in routers:
        router.to_app(app)

# %% ../../nbs/core/routing.ipynb #c9cd90e0
class APIRouter(_ft.APIRouter):
    """APIRouter override that derives route URLs and rt_funcs names from
    `func.__name__` rather than FastHTML 0.14's `nested_name()` (which
    prepends the containing function's name to routes defined inside
    factory functions).

    Restores pre-0.14 flat URL behavior for the `init_*_router(prefix)`
    factory pattern used across the cjm-* ecosystem.
    """

    def __call__(
        self,
        path=None,                # Explicit URL path, or the function itself for bare @rt
        methods=None,             # HTTP methods to register (None = default get+post)
        name=None,                # Route name; defaults to func.__name__ if not provided
        include_in_schema=True,   # OpenAPI schema inclusion
        body_wrap=None            # Body-wrap callable (FastHTML internal)
    ):
        def f(func):
            fn = func.__name__  # flat name, not nested_name(func)
            p_actual = path if (path is not None and not callable(path)) else None
            n = name or fn
            if not p_actual:
                p_actual = '/' if fn == 'index' else '/' + fn
            p_full = self.prefix + p_actual
            wrapped = self._wrap_func(func, p_full, n)
            self.routes.append((func, p_full, methods, n, include_in_schema,
                                body_wrap or self.body_wrap))
            return wrapped
        return f(path) if callable(path) else f

# %% ../../nbs/core/routing.ipynb #48a5e724
# Re-bind HTTP-method shortcuts (get, post, delete, put, patch, options, head, trace)
# to the subclass's __call__ — mirrors FastHTML's own setup at fasthtml.core line 879.
# Without this, rt.get / rt.post etc. would still dispatch to the base class's __call__
# (hard-bound at module-import time) and produce nested_name-prefixed paths.
for _o in _ft.all_meths:
    setattr(APIRouter, _o, partialmethod(APIRouter.__call__, methods=_o))
