"""Routing utilities for FastHTML applications"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/routing.ipynb.

# %% auto 0
__all__ = ['register_routes']

# %% ../../nbs/core/routing.ipynb 3
from typing import Any

# %% ../../nbs/core/routing.ipynb 5
def register_routes(
    app,  # FastHTML app instance
    *routers  # One or more APIRouter instances to register
) -> None:  # No return value
    """Register multiple APIRouter instances to a FastHTML app at once."""
    for router in routers:
        router.to_app(app)
