# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cjm-fasthtml-app-core',
                'doc_host': 'https://cj-mills.github.io',
                'git_url': 'https://github.com/cj-mills/cjm-fasthtml-app-core',
                'lib_path': 'cjm_fasthtml_app_core'},
  'syms': {'cjm_fasthtml_app_core.core': {'cjm_fasthtml_app_core.core.foo': ('core.html#foo', 'cjm_fasthtml_app_core/core.py')}}}
